language: cpp
compiler:
  - gcc
  - clang
  - g++

before_script:
    - cd ../
    - git clone git://github.com/allenbo/common.git
    - cd JConer && cp -R ../common/include/common include
script: make
